### ISSUE TITLE
Make a release with apk

### ISSUE THREAD

**Issue by wvengen** [majido/clipper#1]
It would be useful to make a release and provide a downloadable apk (you can add binaries to releases on Github).

Building for me was not as simple as `./configure && make && make install` (needed to download Android and API 10, modify pom.xml since it overrides ANDROID_HOME, update version of android-maven-plugin to 3.6.1 because older ones didn't find `aapt` properly and much newer ones didn't work with my system-provided maven version).

**Comment by wvengen** [comment]
p.s. just for fun - I used your tool for this https://gist.github.com/wvengen/03b9f57f6c3909a20749

**Comment by majido** [comment]
Thanks for sharing your experience and reporting these issues :+1: . I am happy this utility is being used. 
It appears that the maven file is a bit outdated and needs some love. I will look into it to fix the issues you have encountered. Building a downloadable apk is an improvement too.

**Comment by wvengen** [comment]
Thanks for your reply, I find it quite a useful tool.

**Comment by majido** [comment]
Made a release with APK which should make installation easier.

**Comment by wvengen** [comment]
Thanks!!
